name: Events Demo 1
on:
    pull_request:
        types:
            - opened
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Output the event data
              run: echo "The event data is ${{ toJson(github.event) }}"
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Test the code
              run: npm run test
            - name: Build the code
              run: npm run build
            - name: Deploy the code
              run: echo "Deploying the code..."
